server:
  port: 8001
  servlet:
    context-path: /api
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://101.42.17.125:3306/vse?useSSL=false
    # url: jdbc:mysql://localhost:3306/vse?useSSL=false
    url: jdbc:mysql://139.196.226.104:3306/vse?useSSL=false&serverTimezone=Asia/Shanghai
    username: lyf
    password: Lyf415926
  mail: #邮箱smtp服务配置
    host: smtp.qq.com #服务器邮箱地址，由邮箱官方提供
    username: 417695971@qq.com #账号
    password: drvvnzlqxbddcahd #授权码
    protocol: smtp #一般无需修改
    default-encoding: utf-8
  # redis配置
  redis:
    # 地址
    host: 139.196.226.104
    # 端口，默认为6379
    port: 8010
    password: Lyf415926
    database: 0
    # 连接超时时间
    timeout: 10s
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1m
        time-between-eviction-runs: 1000



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  oss: #阿里云oss服务配置
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5tMGRu9r799jsSPzZQCW
    accessKeySecret: bieHLw8OxSNB0DHCLgRPTslZH4NsoM
    bucketName: vse1

logging:
  level:
    com.baomidou.mybatisplus.core.MybatisPlusInterceptor: debug
